name: 2025_greiner_pseudo-np
channels:
  - conda-forge
dependencies:
  - python=3.12
  - black
  - flake8
  - isort
  - pip
  - matplotlib
  - pandas=2.3.1
  - rdkit=2025.03.4
  - umap-learn=0.5.9.post2
